apiVersion: v1
kind: Pod
metadata:
  name: {{ .Release.Name }}-debug-pod
  namespace: {{ .Values.namespace }}
spec:
  containers:
  - name: debug-container
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: metrics-volume
      mountPath: {{ .Values.volumeMount.mountPath }}
  volumes:
  - name: metrics-volume
    persistentVolumeClaim:
      claimName: {{ .Release.Name }}-metrics-pvc
